---
title: "Grades"
author: "Author: Matthew J. Cossley"
date: "Last update: `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: false
    toc_float:
        collapsed: false
        smooth_scroll: true
    toc_depth: 4
    fig_caption: yes
    # code_folding: show
    number_sections: false
    theme: cosmo
fontsize: 14pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Homework 1 Grades
  
```{r}
library(data.table)
library(ggplot2)

rm(list=ls())

d <- fread('https://crossley.github.io/cogs2020/grades/hw_1_table.csv')

dd <- d[, .(score = unique(score)), .(student_id)]
ggplot(dd, aes(score)) +
  geom_histogram(bins=10)


dd <- d[, .(ans_mean = mean(ans=="correct"),
            ans_err = sd(ans=="correct")/sqrt(.N)), .(ans_labels)]
ggplot(data=dd, aes(x=ans_labels, y=ans_mean)) +
  geom_pointrange(aes(x=ans_labels,
                      ymin=ans_mean-ans_err,
                      ymax=ans_mean+ans_err)) +
  xlab('Problem Number') +
  ylab('Proportion Correct')
```
  
## Homework 2 Grades

```{r}
library(data.table)
library(ggplot2)

rm(list=ls())

d <- fread('https://crossley.github.io/cogs2020/grades/hw_2_table.csv')

dd <- d[, .(score = unique(score)), .(student_id)]
ggplot(dd, aes(score)) +
  geom_histogram(bins=10)


dd <- d[, .(ans_mean = mean(ans=="correct"),
            ans_err = sd(ans=="correct")/sqrt(.N)), .(ans_labels)]
ggplot(data=dd, aes(x=ans_labels, y=ans_mean)) +
  geom_pointrange(aes(x=ans_labels,
                      ymin=ans_mean-ans_err,
                      ymax=ans_mean+ans_err)) +
  xlab('Problem Number') +
  ylab('Proportion Correct')
```
