---
title: "Homework 7 Solutions"
author: "Author: Matthew J. Cossley"
date: "Last update: `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float:
        collapsed: false
        smooth_scroll: true
    toc_depth: 3
    fig_caption: yes
    number_sections: false
    theme: cosmo
fontsize: 14pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Solutions

```{r, message=F, warning=F}
library(data.table)
library(ggplot2)
library(ez)

rm(list = ls())

# This is a cool way to do this... thanks to whoever figured
# this out.
text <- "
        y treatment dose
16.314771         A    1
 8.368833         A    1
16.648996         A    1
16.362147         A    1
32.073207         A    2
22.300250         A    2
25.357165         A    2
28.526398         A    2
39.971164         B    1
52.023267         B    1
43.817967         B    1
36.004954         B    1
14.261715         B    2
18.552692         B    2
18.503924         B    2
17.942446         B    2
41.261117         C    1
35.540394         C    1
42.178416         C    1
33.812308         C    1
18.878661         C    2
21.886978         C    2
20.666682         C    2
24.020948         C    2
"

d <- fread(text)

## define number of levels in each factor
n_treatment <- d[, length(unique(treatment))] # number of treatment levels
n_dose <- d[, length(unique(dose))] # number of dose levels
n <- d[, .N, .(treatment, dose)][, unique(N)] # number of observations at each level

## define Df terms
df_treatment <- n_treatment - 1
df_dose <- n_dose - 1
df_interaction <- df_treatment * df_dose
df_error <- d[, .N] - n_treatment*n_dose

## Define SS terms
ss_treatment <- 0
for(i in d[, unique(treatment)]) {
  ss_treatment <- ss_treatment + (d[treatment==i, mean(y)] - d[, mean(y)])^2
}
ss_treatment <- n_dose * n * ss_treatment

ss_dose <- 0
for(i in d[, unique(dose)]) {
  ss_dose <- ss_dose + (d[dose==i, mean(y)] - d[, mean(y)])^2
}
ss_dose <- n_treatment * n * ss_dose

ss_interaction <- 0
for(i in d[, unique(treatment)]) {
  for(j in d[, unique(dose)]) {
    ss_interaction <- ss_interaction +
      (d[treatment==i & dose==j, mean(y)] -
         (d[treatment==i, mean(y)] + d[dose==j, mean(y)] - d[, mean(y)]))^2
  }
}
ss_interaction <- n * ss_interaction

ss_error <- 0
for(i in d[, unique(treatment)]) {
  for(j in d[, unique(dose)]) {
    for(k in 1:n) {
      ss_error <- ss_error + (d[treatment==i & dose==j][k, y] -
                                d[treatment==i & dose==j, mean(y)])^2
    }
  }
}
ss_error <- ss_error

## Define MS terms
ms_treatment <- ss_treatment / df_treatment
ms_dose <- ss_dose / df_dose
ms_interaction <- ss_interaction / df_interaction
ms_error <- ss_error / df_error

## Define F terms
f_treatment <- ms_treatment / ms_error
f_dose <- ms_dose / ms_error
f_interaction <- ms_interaction / ms_error

## Define Pr(>F)
p_treatment <- pf(f_treatment, df_treatment, df_error, lower.tail=F)
p_dose <- pf(f_dose, df_dose, df_error, lower.tail=F)
p_interaction <- pf(f_interaction, df_interaction, df_error, lower.tail=F)

q_treatment <- qf(0.05, df_treatment, df_error, lower.tail=F)
q_dose <- qf(0.05, df_dose, df_error, lower.tail=F)
q_interaction <- qf(0.05, df_interaction, df_error, lower.tail=F)

theta_hat_obs_treatment <- ms_treatment / ms_error
p_val_treatment <- p_treatment
theta_hat_crit_treatment <- q_treatment

theta_hat_obs_dose <- ms_dose / ms_error
p_val_dose <- p_dose
theta_hat_crit_dose <- q_dose

theta_hat_obs_interaction <- ms_interaction / ms_error
p_val_interaction <- p_interaction
theta_hat_crit_interaction <- q_interaction

prob_1_theta_hat_obs_treatment <- theta_hat_obs_treatment
prob_1_pval_treatment <- p_val_treatment
prob_1_theta_hat_crit_treatment <- theta_hat_crit_treatment

prob_1_theta_hat_obs_dose <- theta_hat_obs_dose
prob_1_pval_dose <- p_val_dose
prob_1_theta_hat_crit_dose <- theta_hat_crit_dose

prob_1_theta_hat_obs_interaction <- theta_hat_obs_interaction
prob_1_pval_interaction <- p_val_interaction
prob_1_theta_hat_crit_interaction <- theta_hat_crit_interaction

d[, subject := 1:.N]
d[, subject := factor(subject)]
d[, treatment := factor(treatment)]
d[, dose := factor(dose)]
r_result <- ezANOVA(data=d,
                    dv=y,
                    wid=subject,
                    between=.(treatment, dose),
                    type=3)
prob_1_r_result <- r_result 

# 2
ans_2a <- "Dose, treatment, and interaction"

# 3
d <- fread('https://crossley.github.io/cogs2020/data/maze_2/maze_2.csv')
d[, rat := 1:.N]
d[, rat := factor(rat)]
d[, maze_odour := factor(maze_odour)]
d[, maze_material := factor(maze_material)]
ans_3 <- ezANOVA(data=d,
                 dv=y,
                 wid=rat,
                 between=.(maze_odour, maze_material),
                 type=3)

# 4
ans_4 <- 19
```

