---
title: "Homework 8 Solutions"
author: "Author: Matthew J. Cossley"
date: "Last update: `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float:
        collapsed: false
        smooth_scroll: true
    toc_depth: 3
    fig_caption: yes
    number_sections: false
    theme: cosmo
fontsize: 14pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Solutions

```{r, message=F, warning=F}
library(data.table)
library(ggplot2)
library(ez)

rm(list = ls())

# problem 1
# 1. Considering the following data and using an appropriate
# ANOVA, test the hypothesis that there are any significant
# differences between mean levels of treatment. Please
# populate the following variables.
text <- "
##             y treatment subject
##  1:  6.867731         A       1
##  2: 10.918217         A       2
##  3:  5.821857         A       3
##  4: 17.976404         A       4
##  5: 31.647539         A       5
##  6: 25.897658         A       6
##  7: 32.437145         A       7
##  8: 33.691624         A       8
##  9: 42.878907         B       9
## 10: 38.473058         B      10
## 11: 47.558906         B      11
## 12: 41.949216         B      12
## 13: 16.893797         B      13
## 14:  8.926501         B      14
## 15: 25.624655         B      15
## 16: 19.775332         B      16
## 17: 39.919049         C      17
## 18: 44.719181         C      18
## 19: 44.106106         C      19
## 20: 42.969507         C      20
## 21: 24.594887         C      21
## 22: 23.910682         C      22
## 23: 20.372825         C      23
## 24: 10.053242         C      24
"
d <- fread(text)
d[, treatment := factor(treatment)]
d[, subject := factor(subject)]

# show that treatment is a between-subject factor
d[, unique(subject), .(treatment)]

# perform the ANOVA
prob_1_r_result <- ezANOVA(data=d,
                           dv=y,
                           wid=subject,
                           between=treatment,
                           type=3)

# problem 2
# 2. Considering the following data and using an appropriate
# ANOVA, test the hypothesis that there are any significant
# differences between mean levels of treatment. Please
# populate the following variables.
text <- "
##             y treatment subject
##  1:  6.867731         A       1
##  2: 10.918217         A       2
##  3:  5.821857         A       3
##  4: 17.976404         A       4
##  5: 31.647539         A       5
##  6: 25.897658         A       6
##  7: 32.437145         A       7
##  8: 33.691624         A       8
##  9: 42.878907         B       1
## 10: 38.473058         B       2
## 11: 47.558906         B       3
## 12: 41.949216         B       4
## 13: 16.893797         B       5
## 14:  8.926501         B       6
## 15: 25.624655         B       7
## 16: 19.775332         B       8
## 17: 39.919049         C       1
## 18: 44.719181         C       2
## 19: 44.106106         C       3
## 20: 42.969507         C       4
## 21: 24.594887         C       5
## 22: 23.910682         C       6
## 23: 20.372825         C       7
## 24: 10.053242         C       8
"
d <- fread(text)
d[, treatment := factor(treatment)]
d[, subject := factor(subject)]

# show that treatment is a within-subject factor
d[, unique(subject), .(treatment)]

# perform the ANOVA
prob_2_r_result <- ezANOVA(data=d,
                           dv=y,
                           wid=subject,
                           within=treatment,
                           type=3)

# problem 3
# 3. Considering the following data and using an appropriate
# ANOVA, test the hypothesis that there are any significant
# differences between mean levels of treatment, mean levels
# of dose, or interactions between treatment and dose.
# Please populate the following variables.
text <- "
##             y treatment dose subject
##  1:  6.867731         A    1       1
##  2: 10.918217         A    1       2
##  3:  5.821857         A    1       3
##  4: 17.976404         A    1       4
##  5: 31.647539         A    2       5
##  6: 25.897658         A    2       6
##  7: 32.437145         A    2       7
##  8: 33.691624         A    2       8
##  9: 42.878907         B    1       1
## 10: 38.473058         B    1       2
## 11: 47.558906         B    1       3
## 12: 41.949216         B    1       4
## 13: 16.893797         B    2       5
## 14:  8.926501         B    2       6
## 15: 25.624655         B    2       7
## 16: 19.775332         B    2       8
## 17: 39.919049         C    1       1
## 18: 44.719181         C    1       2
## 19: 44.106106         C    1       3
## 20: 42.969507         C    1       4
## 21: 24.594887         C    2       5
## 22: 23.910682         C    2       6
## 23: 20.372825         C    2       7
## 24: 10.053242         C    2       8
"
d <- fread(text)
d[, treatment := factor(treatment)]
d[, dose := factor(dose)]
d[, subject := factor(subject)]

# show that treatment is a within-subject factor
d[, unique(subject), .(treatment)]

# show that dose is a between-subject factor
d[, unique(subject), .(dose)]

# perform the ANOVA
prob_3_r_result <- ezANOVA(data=d,
                           dv=y,
                           wid=subject,
                           between=dose,
                           within=treatment,
                           type=3)

# problem 4
# 4. Considering the following data and using an appropriate
# ANOVA, test the hypothesis that there are any significant
# differences between mean levels of treatment, mean levels
# of dose, or interactions between treatment and dose.
# Please populate the following variables.
text <- "
##             y treatment dose subject
##  1:  6.867731         A    1       1
##  2: 10.918217         A    1       2
##  3:  5.821857         A    1       3
##  4: 17.976404         A    1       4
##  5: 31.647539         A    2       5
##  6: 25.897658         A    2       6
##  7: 32.437145         A    2       7
##  8: 33.691624         A    2       8
##  9: 42.878907         B    1       9
## 10: 38.473058         B    1      10
## 11: 47.558906         B    1      11
## 12: 41.949216         B    1      12
## 13: 16.893797         B    2      13
## 14:  8.926501         B    2      14
## 15: 25.624655         B    2      15
## 16: 19.775332         B    2      16
## 17: 39.919049         C    1      17
## 18: 44.719181         C    1      18
## 19: 44.106106         C    1      19
## 20: 42.969507         C    1      20
## 21: 24.594887         C    2      21
## 22: 23.910682         C    2      22
## 23: 20.372825         C    2      23
## 24: 10.053242         C    2      24
"
d <- fread(text)

# show that treatment is a between-subject factor
d[, unique(subject), .(treatment)]
d[, dose := factor(dose)]
d[, subject := factor(subject)]

# show that dose is a between-subject factor
d[, unique(subject), .(dose)]

# perform the ANOVA
prob_4_r_result <- ezANOVA(data=d,
                           dv=y,
                           wid=subject,
                           between=.(treatment, dose),
                           type=3)

# problem 5
# Using an appropriate ANOVA, assess any significant
# differences between runs. If you have multiple
# observations per rat, per run, then be sure to average
# over these values such that you end up with only one
# (mean) observation per rat per run.
d <- fread('https://crossley.github.io/cogs2020/data/maze/maze.csv')
d[, rat := factor(rat)]
d[, maze := factor(maze)]
d[, run := factor(run)]

# show that maze is within-subject
ggplot(d, aes(maze, rat)) +
  geom_point()

# show that run is within-subject
ggplot(d, aes(run, rat)) +
  geom_point()

# perform the ANOVA
dd <- d[, mean(time), .(rat, run)]
ans_5 <- ezANOVA(data=dd,
                           dv=V1,
                           wid=rat,
                           within=.(run),
                           type=3)

# problem 6
# Consider the following sampling distributions of two F
# test statistics. One of these sampling distributions
# corresponds to a repeated measures design, while the other
# corresponds to a factorial design. The observed value of
# the F test statistic (indicated by the dashed lines) is
# 1.5 in both cases.

# repeated measures design uses fewer subjects, and
# therefore has fewer degrees of freedom. This leads the F
# sampling distribution to possess a more extreme critical
# value, and a more extreme critical value corresponds to
# higher tails. Finally, higher tails corresponds to greater
# p-values. Thus, the repeated measures design is on the
# left.
ans_6a <- "repeated on the left, factorial on the right"
ans_6b <- 0.26
```

