---
title: "Lectures"
author: "Author: Matthew J. Cossley"
date: "Last update: `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: false
    toc_float:
        collapsed: true
        smooth_scroll: true
    toc_depth: 4
    fig_caption: yes
    # code_folding: show
    number_sections: false
    theme: cosmo
fontsize: 14pt
---

#### [Lecture 1: Intro to course and R programming](lecture_1.html)
#### [Lecture 2: Descriptive statistics, data types, experiment design](lecture_2.html)
#### [Lecture 3: Probability, Random Variables, confidence intervals](lecture_3.html)
#### [Lecture 4: Binomial Distribution, Binomial Test](lecture_4.html)
#### [Lecture 5: Normal distribution, Normal Test](lecture_5.html)
#### [Lecture 6: t-distribution, single sample t-test](lecture_6.html)
#### Lecture 7: Midterm Exam
#### [Lecture 8: Two-sample t-tests](lecture_7.html)
#### [Lecture 9: One-way ANOVA](lecture_8.html)
#### [Lecture 10: Two-way ANOVA](lecture_9.html)
#### [Lecture 11: Repeated Measures and mixed-design ANOVA](lecture_11.html)
#### [Lecture 12: Simple linear regression](lecture_12.html)
#### [Lecture 13: Multiple regression](lecture_13.html)


| Date     | Week    | Topic                                                 |
|----------+---------+-------------------------------------------------------|
| 21/02/22 | Week 1  | Intro to course and R programming                     |
| 28/02/22 | Week 2  | Descriptive statistics, data types, experiment design |
| 07/03/22 | Week 3  | Probability, Random Variables, confidence intervals   |
| 14/03/22 | Week 4  | Binomial Distribution, Binomial Test                  |
| 21/03/22 | Week 5  | Normal distribution, Normal Test                      |
| 28/03/22 | Week 6  | t-distribution, single sample t-test                  |
| 04/04/22 | Week 7  | Midsem exam                                           |
| 11/04/22 | Recess  | --                                                    |
| 18/04/22 | Recess  | --                                                    |
| 25/04/22 | Week 8  | Two-sample t-tests                                     |
| 02/05/22 | Week 9  | One-way ANOVA                                         |
| 09/05/22 | Week 10 | Two-way ANOVA                                         |
| 16/05/22 | Week 11 | Repeated Measures and mixed design ANOVA              |
| 23/05/22 | Week 12 | Simple Linear Regression                              |
| 30/05/22 | Week 13 | Multiple Regression                                   |
| 14/06/22 | Exams   | --                                                    |
| 24/06/22 | Exams   | --                                                    |
