---
title: "Lecture 1 - Introduction to the course"
author: "Author: Matthew J. Cossley"
date: "Last update: `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float:
        collapsed: false
        smooth_scroll: true
    toc_depth: 3
    fig_caption: yes
    # code_folding: show
    number_sections: false
    theme: cosmo
fontsize: 14pt
---

## What are statistics?

- Very roughly speaking, we can think of statistics as a
mathematical tool for describing data using **descriptive
statistics** and for making decisions on the basis of data
using **inferential statistics**.

- Visualising the data and computing summary statistics like
means and standard deviations are standard approaches for
descriptive statistics.

- Using Null Hypothesis Significance Testing (NHST) is the
standard approach for inferential statistics.


## Why are statistics necessary?
- Basically, statistical methods are useful whenever the
outcomes of an experiment you would like to summarise and
interpret are at least a little bit random.

- For example, imagine trying to determine if a coin is fair
coin (i.e., equal probability of landing heads as landing
tails) or not. Can you make a good decision after just one
flip? Certainly not. This is because you know that the
outcome of each flip is random, so seeing one measly flip
tells you next to nothing. Rather, you need to flip it a
bunch of times, and then think very carefully about the
pattern of outcomes that you observed. The thinking very
carefully part is where statistics comes in to save the day.

- In statistics, we have special terminology to refer the
process that generates random outcomes of an experiment ---
we call is a **random variable**. Any particular single
outcome or sometimes set of random outcomes from an
experiment is called a **sample** from the random variable.


## Why learn to code?
Compared to pointing and clicking your way through data,
**coding is a legit super power**.

- Code is more efficient
- Code is less prone to error
- Code is reusable and reproducible
- Code scales to big data
- Code forces you to think clearly


## Why R?
- It is a real programming language
- It is mature
- It is widely embraced in psychology and neuroscience
- It is widely embraced in data science
- It is relatively easy to learn
- That said, it is not the only good option. Python, for
example, is excellent. Matlab is not quite so excellent, but
it is still widely used in academia. You might even run into
more obscure languages here and there. At the end of the
day, we have to pick one. R is a good plave to start and it
will offer you excellent return on investment.


## Why RStudio?
- RStudio is an excellent place to begin.

- Sensible default and easy to adjust settings.

- Mature and well maintained.

- Fully capable and used by many both within academia and
out in the real data science world.

- That said, there are numerous options for programming in
R. I have old-school computer science friends that edit code
in a plain text file and execute it straight from a
terminal. There is absolutely nothing wrong with this.
Program where you like.


## Why this unit?
- There are numerous ways to learn both statistics and R and
even other units on this campus that will cover similar
material. What makes this unit special?

- Ths unit is special because we will work with and learn
from **real cognitive neuroscience data**. This includes
data from behavioural, neuroimaging, and computational
studies.


## Lets go!
- Install R: Find the download link [here](https://www.r-project.org/)
- Install RStudio: Find the appropriate download link
    [here](https://rstudio.com/products/rstudio/)
- Get going on [homework 1](homework_1.html)