---
title: "Midterm guidelines"
author: "Author: Matthew J. Crossley"
date: "Last update: `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: false
    toc_float:
        collapsed: false
        smooth_scroll: true
    toc_depth: 3
    fig_caption: yes
    number_sections: false
    theme: cosmo
fontsize: 18pt
---

* I will be marking your exam manually -- using my own
actual eyeballs and brain -- so please make every effort to
structure your code coherently.

* Please show your work. Please do not just write numbers in
variable names. Furthermore, your work must include more
than simply calling `t.test()` or `binom.test()` or whatever
else and reading out the values.

* It is correct to perform a normal test only when the
sampling distribution of your test statistic has a normal
distribution.

* It is correct perform a t-test only when the sampling
distribution of your test statistic has a t distribution.

* It is correct to perform a binomial test only when the
sampling distribution of your test statistic has a binomial
distribution.

* For all test statistic sampling distributions that are
continuous, probabilities of specific outcomes are given by
the area under the curve.

* For all test statistic distributions that are discrete,
probabilities of specific outcomes are given by the height
of the points in the plot.

* You do not always need R functions to calculate areas
under curves or heights of bars, especially in simple cases
in which areas might correspond to simple geometric shapes.
There is a reason the midterm prep made you do this sort of
thing.

* Please do not use, refer to, or even think about the
provided code chunks in your answers. They are only good for
making the plot(s) that you are to work with, and giving you
the data.table(s) that you are to work with.

* In particular, if the code chunk defines a variable named
`sig` or `var`, you cannot assume on the basis of this that
the population standard deviation or population variance of
the corresponding random variable is known.

* Also, if you see something in the code chunks that I
provide like `dtri` that does not necessarily mean the
result is a triangular distribution. It is simply a very bad
idea to look at the code. Just look at the plot and use the
data.tables they provide.

* The data in the data.table(s) provided do not necessarily
give you observations from the random variable in question.
That is, some amount of data wrangling may be necessary to
obtain observations from the appropriate random variable.
You need to think very carefully about what the data.table
provides and how the random variable in question is defined
to determine this.