---
title: "Syllabus"
author: "Author: Matthew J. Cossley"
date: "Last update: `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float:
        collapsed: true
        smooth_scroll: true
    toc_depth: 3
    fig_caption: yes
    number_sections: false
    theme: cosmo
fontsize: 14pt
---

## Course Websites
Please reference the following course websites for course
details:

- [Course Materials](https://crossley.github.io/cogs2020/)
- [iLearn](https://ilearn.mq.edu.au/course/view.php?id=62402)
<!-- - [Unit Guide](https://unitguides.mq.edu.au/unit_offerings/123650/unit_guide) -->

## Instructor Information
- **Name:** Dr. Matthew J. Crossley
- **Email:** matthew.crossley@mq.edu.au
- **Office:** Australian Hearing Hub 3.819
- **Office Hours:** Wednesday 3:00 - 5:00

## Tutor Information
- **Name:** Shir Dekel
- **Email:** shirdekel@yahoo.com.au

## Course Schedule
| Activity | Day       | Time                | Location                            |
|----------+-----------+---------------------+-------------------------------------|
| Lecture  | Wednesday | 13:00 PM - 15:00 PM | Online only                         |
| Tutorial | Monday    | 09:00 PM - 11:00 PM | 12 Second Way - 318 Faculty PC Room |
| Tutorial | Monday    | 13:00 PM - 15:00 PM | 12 Second Way - 318 Faculty PC Room |
| Tutorial | Tuesday   | 12:00 PM - 14:00 PM | 12 Second Way - 318 Faculty PC Room |
| Tutorial | Tuesday   | 14:00 PM - 16:00 PM | 12 Second Way - 318 Faculty PC Room |
| Tutorial | Friday    | 12:00 PM - 2:00 PM  | 12 Second Way - 318 Faculty PC Room |
| Tutorial | Friday    | 14:00 PM - 16:00 PM | 12 Second Way - 318 Faculty PC Room |
| Tutorial | Friday    | 16:00 PM - 18:00 PM | 12 Second Way - 318 Faculty PC Room |

- Lectures will be delivered exclusively over Zoom.
- Tutorials will be on campus in the room indiacted above.
- [Lecture Zoom](https://macquarie.zoom.us/j/87043786483)

## Weekly Lectures
- Please see [lectures](lectures.html)

## Course Philosophy
**Useful humans**: By the end of the course, you will be
fully prepared to grapple with the most common data
exploration and analysis situations that occur in cognitive
neuroscience. You will learn how to draw inferences from
data and how to communicate those inferences to others.

**Code everyday**: Learning to program is very much like
learning a new language crossed with learning a new motor
skill. Daily practice and full immersion will help you
immensely. There is no replacement for learning by doing.
Semi-weekly problem sets and quizzes are designed to keep
you motivated and on the hook.

**Learn how to think**:  Intro courses can sometimes leave
students simply consulting a cheat sheet of "apply test X in
situation Y".  Ultimately, the needs of your future research
will be unique. You will need to apply the general
principles of statistics and programming to get the job
done.

**Learn how to teach yourself**: The ultimate goal is for
you to develop the ability to teach yourself more statistics
and more programming. No matter how many courses you take,
your research will eventually take you here. Might as well
get started early.

## Performance Evaluation
- 10% quizzes
- 30% problem sets
- 30% midterm exam
- 30% final exam

**Quizzes**: 10 short online multiple quizzes designed to
provide routine assessment and feedback. Graded on
credit/no-credit basis. The 2 lowest quizzes (missed or
marked non-credit) may be dropped without penalty. These
will not be hard. They are simple nudges to motivate you to
study lecture notes **before** lecture begins.

**Problem sets**: 10 problem sets will be released
approximately 1 per week. These are where most of your
learning will occur. They will require hard work and it is
essential that you take them seriously and commit adequate
time to them. Try to embrace that **code everyday**
lifestyle.

**Midterm exam**: 1 hour exam. I will release it at the
beginning of our normal lecture time and you will have 1
hour to submit your work.

**Final exam**: 2 hour exam. I will release it whenever our
final exam is scheduled by MQ and you will have 2 hours to
submit your work.

**Grading**: No partial credit will be given for any
assignment. Furthermore, you must read the instructions very
carefully and store the results of your code in variables
named exactly as instructed in the assignment. Failure to do
so will result in your work being marked incorrect.

**Attendance**: Attendance is not compulsory, but is highly
recommended. This applies both to lecture and tutorial.
